site_name: RCJ Soccer 2021
theme:
  name: material
  palette:
    primary: green

nav:
  - Home: index.md
  - Qualification:
    - "Africa + Europe": qualification-africa-europe.md
    - Americas: qualification-americas.md
    - "Asia + Pacific": qualification-asia-pacific.md
