site_name: RCJ Soccer 2021
theme:
  name: material
  palette:
    primary: green

nav:
  - Home: index.md
  - Feedback: feedback.md
  - "SoccerSim Qualification":
    - "Africa + Europe": qualification-africa-europe.md
    - Americas: qualification-americas.md
    - "Asia + Pacific": qualification-asia-pacific.md
  - "SoccerSim World Championship":
    - "Group Phase - Home Round": worldcup-home-round.md
    - "Group Phase - Away Round": worldcup-away-round.md
    - "Round of 16": worldcup-b-round-of-16.md
    - "Quarter Finals": worldcup-quarter-finals.md
    - "Semi Finals": worldcup-semi-finals.md
    - "Finals": worldcup-finals.md
  - "SoccerSim SuperTeam": worldcup-superteam.md
