site_name: RCJ Soccer 2021
theme:
  name: material
  palette:
    primary: green

nav:
  - Home: index.md
  - "SoccerSim Qualification":
    - "Africa + Europe": qualification-africa-europe.md
    - Americas: qualification-americas.md
    - "Asia + Pacific": qualification-asia-pacific.md
  - "SoccerSim Worldcup":
    - "Group Phase - Home Round": worldcup-home-round.md
